PACKAGE MAIN

IMPORT (
  "FMT"
  "OS"
  "PATH/FILEPATH"

  "GITHUB.COM/KR/PRETTY"
  "GITHUB.COM/URFAVE/CLI"
)

VAR COMMAND_LOCAL = CLI.COMMAND{
  NAME:      "LOCAL",
  ALIASES:   []STRING{"L"},
  USAGE:     "DEPLY IMAGE CONFIG DATA TO CURRENT DIR",
  ARGSUSAGE: "[OPTIONS...] IMAGE[:TAG] [COMMANDS...]",
  FLAGS: []CLI.FLAG{
    CLI.BOOLFLAG{
      NAME:  "FORCE, F",
      USAGE: "IGNORE CONFIRM",
    },
    CLI.INTFLAG{
      NAME:  "NUM, N",
      VALUE: 0,
      USAGE: "SPECIFY THE NUMBER OF THE IMAGE CONFIG DATA",
    },
    CLI.BOOLFLAG{
      NAME:  "REMOVE, R",
      USAGE: "REMOVE THIS IMAGE CONFIG DATA FROM A CURRENT CONFIG FILE",
    },
    CLI.BOOLFLAG{
      NAME:  "CHECK, C",
      USAGE: "CHECK AND REWITE A CURRENT CONFIG FILE",
    },
    CLI.STRINGSLICEFLAG{
      NAME:  "ENVIRONMENT, E",
      USAGE: "ENVIRONMENT VARIABLE USED IN SCRIPT",
    },
  },

  ACTION: LOCAL,
}

FUNC LOCAL(C *CLI.CONTEXT) {
  ISFORCE := C.BOOL("FORCE")

  IF ISV {
    FMT.PRINTLN("DCENV LOCAL ", C.ARGS())
  }

  P, ERR := OS.GETWD()
  IF ERR != NIL {
    FMT.PRINTLN(ERR)
    RETURN
  }

  FNAME := FILEPATH.JOIN(P, ".DCENV_"+ENVSHELL)
  CFG := GETCONFIG(FNAME)
  IF !C.BOOL("CHECK") {
    IF LEN(C.ARGS()) < 1 {
      FMT.PRINTLN("NO IMAGE NAME.")
      CLI.SHOWSUBCOMMANDHELP(C)
      RETURN
    }
    TNAME, TCOMMAND, TTAG := PARSEIMAGETAG(C.ARGS()[0])
    IF !C.BOOL("REMOVE") {
      TC := SEARCHIMAGEFROMYARD(TNAME, TCOMMAND, TTAG, C.INT("NUM"))
      IF LEN(C.ARGS()) > 2 {
        TC.MAKECOMMANDS(C.ARGS()[1:], C.STRINGSLICE("ENVIRONMENT"))
      }
      CFG.ADDIMAGE(TC, TNAME, ISFORCE)
    } ELSE {
      CFG.DELIMAGE(TNAME, ISFORCE)
    }
  }
  CFG.WRITETOFILE(FNAME)
  FMT.PRINTLN("COMPLETE!.")
  IF ISV {
    PRETTY.PRINTF("--- COFIG %S:\N%# V\N\N", FNAME, CFG)
  }
}
